/* fetchAllEvents */
export const FETCH_ALL_EVENTS_REQUEST = "FETCH_ALL_EVENTS_REQUEST";
export const FETCH_ALL_EVENTS_SUCCESS = "FETCH_ALL_EVENTS_SUCCESS";
export const FETCH_ALL_EVENTS_FAILURE = "FETCH_ALL_EVENTS_FAILURE";

/* fetchAllEventCategories */
export const FETCH_ALL_EVENT_CATEGORIES_REQUEST = "FETCH_ALL_EVENT_CATEGORIES_REQUEST";
export const FETCH_ALL_EVENT_CATEGORIES_SUCCESS = "FETCH_ALL_EVENT_CATEGORIES_SUCCESS";
export const FETCH_ALL_EVENT_CATEGORIES_FAILURE = "FETCH_ALL_EVENT_CATEGORIES_FAILURE";