name: Netlify Release

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set tag version env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Set github identity
      run: |
        git switch -c master
        git config --global user.name "onlinker-admin"
        git config --global user.email "link2link.web@gmail.com"
        git config --global --list
        git config --local --list
    - name: Push to prod
      run: |
        echo "Releasing $RELEASE_VERSION to netlify production"
        npm version $RELEASE_VERSION --no-git-tag-version
        git push origin master && git push origin master:prod --force
